/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\daytona.glb 
*/

import React from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'

export function Daytona(props) {
  const { nodes, materials } = useGLTF('/models/daytona.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[4.338, 10.175, -2.327]} rotation={[0, Math.PI / 6, 0]}>
        <mesh geometry={nodes.knobUp.geometry} material={materials['Gold Rose 18K']} position={[0.751, 0, 0.011]} rotation={[Math.PI / 2, 0, 0]} scale={0.75} />
      </group>
      <group position={[4.338, 10.175, 2.376]} rotation={[0, -Math.PI / 6, 0]}>
        <mesh geometry={nodes.knobDown.geometry} material={materials['Gold Rose 18K']} position={[0.751, 0, 0.011]} rotation={[Math.PI / 2, 0, 0]} scale={0.75} />
      </group>
      <mesh geometry={nodes.OuterRing.geometry} material={materials.OuterRing} position={[-0.01, 11.085, 0.049]} scale={5.245} />
      <mesh geometry={nodes.PointerSeconds.geometry} material={materials['Gold Rose 18K']} position={[-0.646, 11.227, -0.911]} scale={1.959} />
      <mesh geometry={nodes.WristBodyExterior.geometry} material={materials['Platinum polished']} position={[-0.02, 10.109, -0.021]} scale={6.085} />
      <mesh geometry={nodes.LockMiddleIn.geometry} material={materials['Gold Rose 18K']} position={[-0.02, 0.648, 0.105]} scale={4.232} />
      <mesh geometry={nodes.WristBodyInterior.geometry} material={materials['Gold Rose 18K']} position={[-0.02, 10.04, -0.021]} scale={6.917} />
      <mesh geometry={nodes.Object.geometry} material={materials['Gold Rose 18K']} position={[-0.001, 11.067, 0.018]} scale={3.075} />
      <mesh geometry={nodes.InnerRing.geometry} material={materials['Gold Rose 18K']} position={[-0.003, 11.106, 0.04]} scale={4.136} />
      <mesh geometry={nodes.WristInterior.geometry} material={materials['Gold Rose 18K']} position={[-0.017, 5.7, -0.021]} scale={9.976} />
      <mesh geometry={nodes.LockOuter.geometry} material={materials['Gold Rose 18K']} position={[-0.02, 0.819, -0.04]} scale={6.94} />
      <mesh geometry={nodes.WristExterior.geometry} material={materials['Platinum polished']} position={[-0.02, 5.565, -0.021]} scale={9.941} />
      <mesh geometry={nodes.DialDigits.geometry} material={materials.DigitsMaterial} position={[-0.036, 11.006, 0.717]} scale={2.795} />
      <mesh geometry={nodes.DialsLines.geometry} material={materials['Gold Rose 18K']} position={[0.067, 11.008, 0.987]} scale={2.817} />
      <mesh geometry={nodes.Dial.geometry} material={materials.Dial} position={[0.027, 10.957, 0.101]} scale={3.753} />
      <mesh geometry={nodes.KnobMiddle.geometry} material={materials['Gold Rose 18K']} position={[5.802, 10.147, -0.021]} scale={[1.076, 1.033, 1.076]} />
      <mesh geometry={nodes.CoverInside.geometry} material={materials['Gold Rose 18K']} position={[-0.01, 9.234, 0.049]} scale={5.245} />
      <mesh geometry={nodes.MainBody.geometry} material={materials['Gold Rose 18K']} position={[0.339, 10.057, -0.041]} scale={6.42} />
      <mesh geometry={nodes.LockMiddleOut.geometry} material={materials['Gold Rose 18K']} position={[-0.03, 0.553, 0.103]} scale={4.502} />
      <mesh geometry={nodes.BoxMarker.geometry} material={materials['Gold Rose 18K']} position={[-0.015, 11.067, 1.682]} scale={3.496} />
      <mesh geometry={nodes.PointerMiddles.geometry} material={materials['Gold Rose 18K']} position={[0.017, 11.161, 0.891]} scale={1.82} />
      <mesh geometry={nodes.DialRipples.geometry} material={materials['Gold Rose 18K']} position={[0.014, 10.977, 0.898]} scale={2.553} />
      <mesh geometry={nodes.KnobDots.geometry} material={materials['Gold Rose 18K']} position={[6.495, 10.145, 0.002]} scale={0.595} />
      <mesh geometry={nodes.bgesferas.geometry} material={materials.backsphere} position={[0, 10.863, 0]} scale={[3.307, 0.1, 3.307]} />
      <mesh geometry={nodes.NightMarkers.geometry} material={materials.markerFluor} position={[-0.017, 11.061, 0.218]} scale={3.436} />
      <mesh geometry={nodes.DialPointerHours.geometry} material={materials['Gold Rose 18K']} position={[-1.386, 11.021, -0.217]} rotation={[Math.PI, -1.398, Math.PI]} scale={0.51} />
      <mesh geometry={nodes.DialPointerSeconds.geometry} material={materials['Gold Rose 18K']} position={[2.131, 11.021, -0.25]} rotation={[Math.PI, -1.398, Math.PI]} scale={0.51} />
      <mesh geometry={nodes.DialPointerMinutes.geometry} material={materials['Gold Rose 18K']} position={[0.362, 11.021, 1.714]} rotation={[Math.PI, -1.398, Math.PI]} scale={0.51} />
      <mesh geometry={nodes.LogoFront.geometry} material={materials.Gold} position={[-0.08, 11.051, -2.924]} scale={[0.506, 0.705, 0.506]} />

      <mesh geometry={nodes.PointerHourColor.geometry} material={materials.backsphere} position={[-0.573, 11.095, -0.428]} scale={1.197} />
      <mesh geometry={nodes.PointerHours.geometry} material={materials['Gold Rose 18K']} position={[-0.552, 11.094, -0.399]} scale={1.221} />
      <mesh geometry={nodes.PointerMinutes.geometry} material={materials['Gold Rose 18K']} position={[1.245, 11.159, -0.709]} rotation={[0, -1.049, 0]} scale={2.152} />
      <mesh geometry={nodes.PointerMinutesColor.geometry} material={materials.backsphere} position={[1.239, 11.156, -0.72]} rotation={[0, -1.049, 0]} scale={2.151} />
      <mesh geometry={nodes.glass.geometry} material={materials.glass} position={[-0.012, 11.338, -0.038]} rotation={[0, -Math.PI / 2, 0]} scale={4.148} >
        <MeshTransmissionMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/daytona.glb')
