/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Daytona2.glb 
*/
import * as THREE from 'three'

import React from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import { createMaterials } from './materials'
import { useMemo } from 'react'

export function Daytona(props) {
  const { nodes, materials } = useGLTF('/models/Daytona2.glb')
  const { rolexGold, rolexSteel, rolexFind } = useMemo(() => {
    return createMaterials()
  }, [])
  console.log(materials)
  materials['Hard rough plastic - tuscan red.008'].color = new THREE.Color(0xe0875e)
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 7.842, 0.007]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group >
          <group position={[1.95, 4.32, -293]} scale={[0.91, 0.92, 1]}>
            <mesh geometry={nodes.boxes001.geometry} material={rolexFind} position={[0, 0, -8.459]} />
          </group>
          <group position={[10.247, 207.967, -295.5]} scale={[1.165, 1.165, 0.07]}>
            <mesh geometry={nodes.ciferblat001.geometry} material={materials['Hard white shiny']} position={[0, 0, -155.426]} />
          </group>
          <group position={[1, 9.4, -292]} scale={[0.9, 0.9, 1]} visible={true}>
            <mesh geometry={nodes.deleniya001.geometry} material={materials['Hard rough plastic - tuscan red.008']} position={[0, 0, -14.279]} />
          </group>
          <group position={[4, -0.6, -292]}>
            <mesh geometry={nodes.h_pointer001.geometry} material={materials['Hard rough plastic - tuscan red.010']} position={[0, 0, -10.88]} />
          </group>
          <group position={[0, 0, -290]}>
            <mesh geometry={nodes.krepeg001.geometry} material={materials['Hard rough plastic - tuscan red.016']} position={[0, 0, -13.575]} />
          </group>
          <group position={[0, -0.605, -314.176]} rotation={[-0.079, 0, 0]}>
            <mesh geometry={nodes.krown001.geometry} material={materials['Hard rough plastic - tuscan red.017']} position={[0, 0.894, -11.365]} />
          </group>
          <group position={[0.806, -0.58, -293]} rotation={[0, 0, 0.017]} scale={[0.945, 0.945, 1]}>
            <mesh geometry={nodes.lodochka001.geometry} material={materials['Hard rough plastic - tuscan red.003']} position={[0, 0, -8.459]} />
          </group>
          <group position={[3, 0, -298.9]} rotation={[0, 0, -1.152]}>
            <mesh geometry={nodes.m_pointer001.geometry} material={materials['Hard rough plastic - tuscan red.018']} position={[0, 0, -10.88]} />
          </group>
          <group position={[1, 9.4, -292]} scale={[0.9, 0.9, 1]}>
            <mesh geometry={nodes.riples001.geometry} material={materials['Hard rough plastic - tuscan red.019']} position={[0, 0, -14.279]} />
          </group>
          <group position={[4, 0, -294.6]}>
            <mesh geometry={nodes.secomds_pointer001.geometry} material={materials['Hard rough plastic - tuscan red']} position={[0, 0, -10.88]} />
          </group>
          <group position={[1, -1, -292]} scale={[0.955, 0.955, 1]}>
            <mesh geometry={nodes.strelky001.geometry} material={materials['Hard rough plastic - tuscan red.011']} position={[0, 0, -14.279]} />
          </group>
        </group>
        <mesh geometry={nodes.digits001.geometry} material={materials['Hard white rough']} position={[0, 0, -14.279]} />
        <mesh geometry={nodes.inner_ring001.geometry} material={materials['Hard rough plastic - tuscan red.005']} position={[-0.24, 0.18, -235]} scale={[1, 1.01, 1]} />
        <mesh geometry={nodes.knob001.geometry} material={rolexGold} />
        <mesh geometry={nodes.knob2001.geometry} material={rolexGold} />
        <mesh geometry={nodes.korpus001.geometry} material={rolexGold} position={[0, -2, -292]} />
        <mesh geometry={nodes.krishka001.geometry} material={materials['Hard rough plastic - tuscan red.012']} />
        <mesh geometry={nodes.Lock001.geometry} material={materials['Hard rough plastic - tuscan red.014']} />
        <mesh geometry={nodes.lock2001.geometry} material={materials['Hard rough plastic - tuscan red.001']} scale={[1, 1.06, 1]} />
        <mesh geometry={nodes.logo2001.geometry} material={materials['Hard rough plastic - tuscan red.020']} />
        <mesh geometry={nodes.outer_ring001.geometry} material={materials.outer_ring} position={[0, 0, -292]} />
        <mesh geometry={nodes.ushko001.geometry} material={rolexGold} />
        <mesh geometry={nodes.vidro__vidro_0.geometry} position={[-70.905, -233.513, 727]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={72.344} >
          <MeshTransmissionMaterial transmission={1} thickness={0.001} ior={1.7} side={2} opacity={1} color={'#ffffff'} />
        </mesh>
        <mesh geometry={nodes.wristband001.geometry} material={rolexSteel} />

        <mesh geometry={nodes.wristband3001.geometry} material={rolexSteel} />
        <mesh geometry={nodes.wristband2001.geometry} material={rolexGold} />
        <mesh geometry={nodes.wristband4001.geometry} material={rolexGold} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Daytona2.glb')
