/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 --transform --keepmeshes --simplify --keepgroups --keepnames --shadows --instance --keepmaterials .\Daytona.glb 
Files: .\Daytona.glb [72.63MB] > C:\discord\marca-relojes\public\models\home\Daytona-transformed.glb [3.4MB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Daytona-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">

      </group>
    </group>
  )
}

useGLTF.preload('/Daytona-transformed.glb')
