/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Daytona.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Daytona.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.OuterRing.geometry} material={materials.OuterRing} />
      <mesh geometry={nodes.PointerSeconds.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.WristBodyExterior.geometry} material={materials['Platinum polished']} />
      <mesh geometry={nodes.LockMiddleIn.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.WristBodyInterior.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.MarkerGold.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.InnerRing.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.WristInterior.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.LockOuter.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.WristExterior.geometry} material={materials['Platinum polished']} />
      <mesh geometry={nodes.DialDigits.geometry} material={materials.DigitsMaterial} />
      <mesh geometry={nodes.DialsLines.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.Dial.geometry} material={materials.Dial} />
      <mesh geometry={nodes.CoverInside.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.MainBody.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.LockMiddleOut.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.BoxMarker.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.PointerMiddles.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.DialRipples.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.bgesferas.geometry} material={materials.backsphere} />
      <mesh geometry={nodes.NightMarkers.geometry} material={materials.markerFluor} />
      <mesh geometry={nodes.LogoFront.geometry} material={materials.Gold} />
      <mesh geometry={nodes.glass.geometry} material={materials.glass} />
      <mesh geometry={nodes.knobUp.geometry} material={materials['Gold Rose 18K']} position={[4.338, 10.175, -2.327]} rotation={[Math.PI / 2, 0, -Math.PI / 6]} />
      <mesh geometry={nodes.knobDown.geometry} material={materials['Gold Rose 18K']} position={[4.338, 10.175, 2.376]} rotation={[Math.PI / 2, 0, Math.PI / 6]} />
      <mesh geometry={nodes.PointerHourColor.geometry} material={materials.backsphere} />
      <mesh geometry={nodes.PointerHours.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.PointerMinutes.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.PointerMinutesColor.geometry} material={materials.backsphere} />
      <mesh geometry={nodes.DialPointerSeconds.geometry} material={materials['Gold Rose 18K']} position={[1.77, 11.021, -0.089]} />
      <mesh geometry={nodes.DialPointerMinutes.geometry} material={materials['Gold Rose 18K']} position={[0.01, 11.021, 1.871]} />
      <mesh geometry={nodes.DialPointerHours.geometry} material={materials['Gold Rose 18K']} position={[-1.738, 11.021, -0.058]} />
      <mesh geometry={nodes.KnobDots.geometry} material={materials['Gold Rose 18K']} />
      <mesh geometry={nodes.KnobMiddle.geometry} material={materials['Gold Rose 18K']} position={[5.817, 10.147, -0.021]} />
    </group>
  )
}

useGLTF.preload('/Daytona.glb')
